# Generated by Django 5.2.5 on 2025-08-24 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField()),
                ('category', models.CharField(choices=[('Workshop', 'Workshop'), ('Sports', 'Sports'), ('Hackathon', 'Hackathon'), ('Art', 'Art'), ('Conference', 'Conference'), ('Other', 'Other')], default='Other', max_length=50)),
                ('location_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('ticket_limit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date_time'],
            },
        ),
    ]
